
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://reardona.github.io/meow/"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: "/meow"

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Ashley Reardon"
title: "Ashley L Reardon"
description: "Professional website of Ashley Reardon, human performance researcher and gaming enthusiast."
keywords: "reardon, ashley, human performance, research, gaming"
favicon: "/img/favicon1.ico"

################
# Header layout #
################

black-favicon: "/img/favicon1.ico"


background-img: "../img/ffs.jpg" 


##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Life begins at the end of your comfort zone."
  - text: "Where’s your will to be weird?"

me-img: "/img/author1.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False #I changed this. 1/12 was originally True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"


############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "May 2016 - Present"
    description: "Quantum Improvements Consulting, did more stuff"
  - image: "/img/timeline/baracktocat.jpg"
    date: "August 2016 - May 2018"
    description: "University of Central Florida, Master of Modeling and Simulation"
  - image: "/img/timeline/baracktocat.jpg"
    date: "June 2016 - May 2016"
    description: "Prodigy Lab, Did stuff"
  - image: "/img/timeline/baracktocat.jpg"
    date: "August 2013 - May 2016"
    description: "University of Central Florida, Bachelor of Arts in Psychology"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "reardona@knights.ucf.edu"


################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Ashley Reardon holds a Bachelor of Arts in Psychology from the University of Central Florida, and will be receiving her Masters degree in Modeling and Simulation from the University of Central Florida in May of 2018. When shHer research focus stems from x, y,z, experiences as an undergrad, and has grown since her time in grad school. Her work include x, y, z. awesome person."
author_blurb_image: "/img/author1.jpg"

##################
# Social Buttons #
##################

social:
  #- title: "facebook"
    #url: "https://facebook.com/"
  #- title: "twitter"
    #url: "https://twitter.com/"
  #- title: "github"
    #url: "https://github.com/PanosSakkos/personal-jekyll-theme"
  #- title: "bitcoin"
    #url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  #- title: "rss"
    #url: "/feed.xml"
   - title: "linkedin"
     url: "https://linkedin.com/in/ashleylaurenreardon/"
 


############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

#keybase-username: johnsmith
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Contact: 'contact'
  #CV: 'cv'


# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
